HardCodeProject/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;
using HardCodeProject.Models;
using System.Text.Json.Serialization;
using Newtonsoft.Json;
using System.Text;
using HardCodeProject.Models.ViewModels;

namespace HardCodeProject.Controllers
{
    public class MainController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7125/api");
        private readonly HttpClient _client;
        private List<ProductViewModel> _products;
        private List<CategoryViewModel> _categories;
        private bool sortIndex;
        private void Initialize()
        {
            HttpResponseMessage productResponse = _client.GetAsync(_client.BaseAddress + "/Products/GetProducts").Result;
            HttpResponseMessage categoryResponse = _client.GetAsync(_client.BaseAddress + "/Categories/GetCategories")
                    .Result;
           

            if (productResponse.IsSuccessStatusCode && categoryResponse.IsSuccessStatusCode)
            {
                string dataProduct = productResponse.Content.ReadAsStringAsync().Result;
                string dataCategory = categoryResponse.Content.ReadAsStringAsync().Result;

                _products = JsonConvert.DeserializeObject<List<ProductViewModel>>(dataProduct);
                _categories = JsonConvert.DeserializeObject<List<CategoryViewModel>>(dataCategory);

            }
        }
        public MainController()
        {
            sortIndex = false;
            _client = new HttpClient();
            _client.BaseAddress = baseAddress;
            Initialize();
        }
 
        #region ProductActions
        public IActionResult Index()
        {
           
            ViewBag.Categories = _categories;
        
            var products = from p in _products select p;
            
            return View(products.ToList());
        }

        [HttpPost]
        public IActionResult Index(string filter)
        {
            ViewBag.Categories = _categories;
            var lstProduct = from p in _products select p;
            switch (filter)
            {

                case "ProductName":
                    lstProduct = lstProduct.OrderBy(p => p.NameProduct).ToList();
                    break;

                case "DescriptionProduct":
                    lstProduct = lstProduct.OrderBy(p => p.DescriptionProduct).ToList();
                    break;
                case "CountProduct":
                    lstProduct = lstProduct.OrderBy(p => p.CountProduct).ToList();
                    break;
                case "CategoryProduct":
                    lstProduct = lstProduct.OrderBy(p => p.CategoryId).ToList();
                    break;
                default:
                    lstProduct = lstProduct.OrderByDescending(p => p.NameProduct).ToList();
                    break;

            }
            return View(lstProduct.ToList());
        }


        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Message = _categories;
            return View(new ViewProduct());
        }

        [HttpPost]
        public IActionResult Create([Bind("Img,Name,Description,Count,Category")] ViewProduct product)
        {
            if (product == null)
                return NotFound();
            else
            {
                ProductViewModel newProduct = new ProductViewModel()
                {
                    ImgProduct = product.Img,
                    NameProduct = product.Name,
                    DescriptionProduct = product.Description,
                    CountProduct = product.Count,
                    CategoryId = product.Category,
                };

                var data = JsonConvert.SerializeObject(newProduct);
                StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                HttpResponseMessage productCreate = _client.PostAsync
                    (_client.BaseAddress + $"/Products/PostProduct",content).Result;

                if (productCreate.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                return NotFound();
            }
        }

        public IActionResult CloserLook(int id)
        {
            HttpResponseMessage productResponse = _client.GetAsync(_client.BaseAddress + $"/Products/GetProduct/{id}").Result;
            if(productResponse.IsSuccessStatusCode) 
            {
                var data = productResponse.Content.ReadAsStringAsync().Result;
                ProductViewModel myProduct = JsonConvert.DeserializeObject<ProductViewModel>(data);
                return View(myProduct);
            }
            return NotFound();
        }
        #endregion

        #region CategoriesActions
        public IActionResult IndexCategory()
        {
            var categories = from c in _categories select c;
            return View(categories.ToList());
        }

        public IActionResult CreateCategory()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateCategory([Bind("Name")]ViewCategory category) 
        {
            if(category == null)
                return NotFound();
            CategoryViewModel newCategory = new CategoryViewModel
            {
                Name = category.Name,
            };
            var data = JsonConvert.SerializeObject(newCategory);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
            HttpResponseMessage categoryCreate = _client.PostAsync(_client.BaseAddress + "/Categories/PostCategory", content).Result;
            if (categoryCreate.IsSuccessStatusCode)
            {
                return RedirectToAction("IndexCategory");
            }
            return NotFound();
        }

        [HttpGet]
        public IActionResult DeleteCategory(int id)
        {

            var category = _categories.FirstOrDefault(u => u.Id == id);
            if (category != null)
            {
                HttpResponseMessage categoryDelete = _client.DeleteAsync(_client.BaseAddress + $"/Categories/DeleteCategory/{id}").Result;
                if (categoryDelete.IsSuccessStatusCode)
                {
                    return RedirectToAction("IndexCategory");
                }
            }

            return NotFound();
        }

        #endregion
    }
}

HardCodeProject/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HardCodeProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HardCodeProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">HardCodeProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                   
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Main" asp-action="Index">List Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Main" asp-action="IndexCategory">List Category</a>
                        </li>


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HardCodeProject - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>